ardupilot_default_airframe: gazebo-iris
ardupilot_dir: ~/ardupilot
global_coordinates:
  altitude: 90.0
  latitude: 38.736832
  longitude: -9.137977
# px4_default_airframe: gazebo-calssic_iris # Default
# px4_default_airframe: none_iris # PX4 v1.14.3
px4_default_airframe: iris # PX4 v1.13.0
px4_dir: /home/longbin/Desktop/PX4-Autopilot
